apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-username/your-cert-manager-repo.git'
    path: 'path/to/your/cert-manager/configuration'
    targetRevision: HEAD 
  destination:
    server: 'https://kubernetes.default.svc' 
    namespace: cert-manager 
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 