apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-username/your-mongodb-repo.git'
    path: 'path/to/your/mongodb/configuration'
    targetRevision: HEAD 
  destination:
    server: 'https://kubernetes.default.svc' 
    namespace: mongodb 
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 