apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-username/your-rabbitmq-cluster-repo.git'
    path: 'path/to/your/rabbitmq-cluster/configuration'
    targetRevision: HEAD 
  destination:
    server: 'https://kubernetes.default.svc' 
    namespace: rabbitmq-cluster 
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 