apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-messaging-topology
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-username/your-rabbitmq-messaging-topology-repo.git'
    path: 'path/to/your/rabbitmq-messaging-topology/configuration'
    targetRevision: HEAD 
  destination:
    server: 'https://kubernetes.default.svc' 
    namespace: rabbitmq-messaging-topology 
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 